server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      force: true
  shutdown: graceful

spring:
  application:
    name: rest-cars-api
  profiles:
    active: dev
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: ${spring.jpa.open-in-view}
    properties:
      hibernate:
        enable_lazy_load_no_trans: ${spring.jpa.properties.hibernate.enable_lazy_load_no_trans}
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}
    show-sql: ${spring.jpa.show-sql}
  h2:
    console:
      enabled: ${spring.h2.console.enabled}
      path: ${spring.h2.console.path}
      settings:
        web-allow-others: ${spring.h2.console.settings.web-allow-others}
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null

springdoc:
  swagger-ui:
    enabled: ${springdoc.swagger-ui.enabled}
    operations-sorter: method
    tags-sorter: ${springdoc.swagger-ui.tags-sorter}
    display-request-duration: ${springdoc.swagger-ui.display-request-duration}

openapi-servers-urls: ${openapi-servers-urls}
